package com.pikachu.book.cls.sql.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pikachu.book.cls.sql.F2BooksData;

import com.pikachu.book.cls.sql.dao.F2BooksDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig f2BooksDataDaoConfig;

    private final F2BooksDataDao f2BooksDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        f2BooksDataDaoConfig = daoConfigMap.get(F2BooksDataDao.class).clone();
        f2BooksDataDaoConfig.initIdentityScope(type);

        f2BooksDataDao = new F2BooksDataDao(f2BooksDataDaoConfig, this);

        registerDao(F2BooksData.class, f2BooksDataDao);
    }
    
    public void clear() {
        f2BooksDataDaoConfig.clearIdentityScope();
    }

    public F2BooksDataDao getF2BooksDataDao() {
        return f2BooksDataDao;
    }

}
